baror/urls.py
from django.urls import path
from . import views

app_name = 'barors'
urlpatterns = [
    path('', views.list_of_barors, name='all-barors'),
    path('addround/', views.add_baror, name='add-baror'),
    path('<pk>/editround/', views.edit_baror, name='edit-baror'),
    path('addsoldier/', views.add_soldier_to_round, name='add-soldier-to-round'),
    path('<pk>/barorReady/', views.baror_is_ready, name='baror-is-ready'),
    path('<pk>/manageround/', views.start_baror_page, name='start-baror'),
    path('<pk>/manageround/soldierendthebaror/', views.manage_running_round, name='manage-soldier-in-round'),
]

gibush/urls.py
from django.contrib import admin
from django.urls import path, include
from user_management import views
from django.conf.urls.static import static
from . import settings




urlpatterns = [
    path('admin/', admin.site.urls),
    # Home page
    path('', views.edit_home_path, name='edit-home-page'),
    path('home/', views.home_page, name='home-page'),
    # Apps
    path('soldiers/', include('soldiers.urls')),
    path('barors/', include('baror.urls')),
    path('shalishut/', include('shalishut.urls')),
    path('clinic/', include('clinic.urls')),
    path('commander/', include('commander.urls')),
    path('users/', include('user_management.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_management/urls.py
from django.urls import path
from . import views

app_name = 'user_management'
urlpatterns = [
    # Users
    path('', views.menu, name='menu-users'),
    path('adduser/', views.add_user, name='add-user-users'),
    path('edituser/<pk>', views.edit_user, name='edit-user-users'),
    path('search/', views.search, name='search-users'),
    path('login/', views.login_page, name='login-page'),
    path('logout/', views.logout_page, name='logout-page'),
    
    
]

user_management/models.py
from django.db import models

# Create your models here.

user_management/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from soldiers.models import Soldier
from .decorators import allowed_users, login_required
from django.contrib.auth.models import User, Group
from django.db.models import Q
from django.contrib import messages


from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

@allowed_users(allowed_roles=['Commander'])
def menu(request):
    all_users = User.objects.all()
    inactive_users = User.objects.exclude(is_active=True)
    return render(request, 'users_menu.html', {'users': {'all': all_users, 'inactive': inactive_users}, 'search_url': 'user_management:search-users'})


@allowed_users(allowed_roles=['Commander'])
def add_user(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = request.POST.get('username')
            messages.success(
                request, f"The user {username} has been added successfully")
            return redirect("user_management:menu-users")
        else:
            form_error_handling(request, form)
    return render(request, 'add_user.html', {'form': form})


@allowed_users(allowed_roles=['Commander'])
def edit_user(request, pk):
    current_user = request.user
    user_edit = User.objects.get(id=pk)
    groups = Group.objects.all()
    if user_edit.is_superuser and not current_user.is_superuser:
        messages.error(request, f"Sorry, only the admin can edit a superuser.")
        return redirect("user_management:menu-users")
    if request.method == 'POST':
        username_edit = request.POST.get('username')
        firstname_edit = request.POST.get('first_name')
        lastname_edit = request.POST.get('last_name')
        email_edit = request.POST.get('email')
        is_active_edit = request.POST.get('is_active')
        groups_edit = request.POST.getlist('groups')
        try:
            # Is active?
            if current_user.username != user_edit.username:
                if is_active_edit == 'on':
                    user_edit.is_active = True
                    messages.success(request, f"The user {user_edit.username} has been activated.")
                else:
                    user_edit.is_active = False
                    messages.warning(request, f"The user {user_edit.username} has been deactivated.")
            elif is_active_edit != 'on':
                messages.error(request, f"You can't deactivate your account.")

            # Change username:
            if user_edit.username != username_edit:
                user_edit.username = username_edit

            # Personal details:
            if firstname_edit:
                user_edit.first_name = firstname_edit
            else:
                user_edit.first_name = ''
            if lastname_edit:
                user_edit.last_name = lastname_edit
            else:
                user_edit.last_name = ''
            if email_edit:
                user_edit.email = email_edit
            else:
                user_edit.email = ''

            # Save
            user_edit.save()

            # Groups
            user_edit.groups.set(groups_edit)

            messages.success(
                request, f"The user {username_edit} has been edited successfully")
            return redirect("user_management:menu-users")
        except Exception as ex:
            messages.error(request, f"ERROR! {ex}")
    return render(request, 'edit_user.html', {'user_edit': user_edit, 'groups': groups})


def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You logged in as {username}.")
                return redirect('home-page')
            else:
                messages.error(
                    request, "Your username and password didn't match. Please try again.")
        else:
            form_error_handling(request, form)
    return render(request, 'login.html', {'form': form})


# @login_required
def search(request):
    search_req = request.GET.get('search')
    all_users = User.objects.filter(
        Q(username__istartswith=search_req) |
        Q(first_name__istartswith=search_req) |
        Q(last_name__istartswith=search_req)
    )
    inactive_users = all_users.exclude(is_active=True)
    return render(request, 'users_menu.html', {'users': {'all': all_users, 'inactive': inactive_users}, 'search_url': 'user_management:search-users'})


# @login_required       # this is in comment for the welcome page
def home_page(request):
    status = {}
    for s in Soldier.SoldierStatus:
        key = str(s).upper().replace(' ', '_')
        status[key] = Soldier.objects.filter(soldier_status=s)
    return render(request, 'home.html', {'status': status})


# to get path 'home/'
def edit_home_path(request):
    return redirect('home-page')


def logout_page(request):
    logout(request)
    messages.info(request, "You have logged out.")
    return redirect("home-page")


def form_error_handling(request, form):
    for key in form.errors.keys():
        for error in form.errors.get(key):
            messages.error(request, f'ERROR! {error}')

user_management/templates/add_user.html
{% extends "home_users.html" %}
{% block users-main %}
<div class="container-fluid">

    <div style="margin: auto;" class="col-lg-6">
        <!-- Collapsable Card Example -->
        <div class="card shadow mb-4">
            <!-- Card Header - Accordion -->
            <div class="d-block card-header py-3">
                <h3 class="m-0 font-weight-bold text-primary">Add User</h3>
            </div>

            <!-- Card Content - Collapse -->
            <div class="collapse show" id="collapseCardExample">
                <div class="continer">
                    <div class="card-body">
                        <div class="form-group">
                            <form class="form-control-lg" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <table>
                                    <tr>
                                        <td>{{ form.username.label_tag }}</td>
                                        <td>{{ form.username }}</td>
                                    </tr>
                                    <tr>
                                        <td>{{ form.password1.label_tag }}</td>
                                        <td>{{ form.password1 }}</td>
                                    </tr>
                                    <tr>
                                        <td>{{ form.password2.label_tag }}</td>
                                        <td>{{ form.password2 }}</td>
                                    </tr>
                                </table>
                                </br>
                                <input class="btn btn-success float-end" type="submit" value="Add">
                            </form>
                        </div>
                        <a href="{% url 'user_management:menu-users' %}"><button
                                class="btn btn-outline-secondary float-start mb-4 ">Back</button></a>
                    </div>
                    <br>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

user_management/templates/edit_user.html
{% extends "home_users.html" %}
{% block users-main %}
<div class="container-fluid">

    <div style="margin: auto;" class="col-lg-10">
        <!-- Collapsable Card Example -->
        <div class="card shadow mb-4">
            <!-- Card Header - Accordion -->
            <div class="d-block card-header py-3">
                <h3 class="m-0 font-weight-bold text-primary">Edit User</h3>
            </div>

            <!-- Card Content - Collapse -->
            <div class="collapse show" id="collapseCardExample">
                <div class="continer">
                    <div class="card-body">
                        <div class="form-group">
                            <div>Select the user permissions.</div> <br>
                            <form class="form-control-lg" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <table>
                                    <tr>
                                        <th>
                                            <label for="id_username">Username:</label>
                                        </th>
                                        <td>
                                            <input type="text" name="username" maxlength="150" autocapitalize="none"
                                                autocomplete="username" id="id_username" value="{{user_edit.username}}">
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>
                                            <label for="id_first_name">First name:</label>
                                        </th>
                                        <td>
                                            <input type="text" name="first_name" maxlength="150" id="id_first_name"
                                                value="{{user_edit.first_name}}">
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>
                                            <label for="id_last_name">Last name:</label>
                                        </th>
                                        <td>
                                            <input type="text" name="last_name" maxlength="150" id="id_last_name"
                                                value="{{user_edit.last_name}}">
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>
                                            <label for="id_email">Email address:</label>
                                        </th>
                                        <td>
                                            <input type="email" name="email" maxlength="254" id="id_email"
                                                value="{{user_edit.email}}">
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>
                                            <label for="id_is_active">Active:</label>
                                        </th>
                                        <td>
                                            {% if user_edit.is_active %}
                                            <input type="checkbox" name="is_active" checked>
                                            {% else %}
                                            <input type="checkbox" name="is_active">
                                            {% endif%}
                                            <br>
                                            <span class="helptext">Designates whether this user should be treated as
                                                active.
                                                Unselect
                                                this instead of deleting accounts.</span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>
                                            <label for="id_groups">Groups:</label>
                                        </th>
                                        <td>
                                            <fieldset>
                                                {% for group in groups %}
                                                {% if group in user_edit.groups.all %}
                                                <input type="checkbox" name="groups" value="{{group.id}}" checked>
                                                {{group.name}}</input></br>
                                                {% else %}
                                                <input type="checkbox" name="groups" value="{{group.id}}">
                                                {{group.name}}</input></br>
                                                {% endif %}
                                                {% endfor %}
                                            </fieldset>
                                            <span class="helptext">The groups this user belongs to. A user will get all
                                                permissions
                                                granted to each of their groups.</span>
                                        </td>
                                    </tr>
                                </table>
                                </br>
                                <input class="btn btn-lg btn-success float-end" type="submit" value="Set">
                            </form><a href="{% url 'user_management:menu-users' %}"><button
                                    class="btn btn-lg btn-outline-secondary float-start mb-4 ">Back</button></a>
                        </div>
                    </div>
                    <br>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

user_management/templates/home_users.html
{% extends "base.html" %}
{% block main %}
<div class="container-fluid">

    <!-- Page Heading -->
    <div style="text-align:center;" class="mb-4">
        <h1 class="mb-0 text-gray-800" style="font-weight: bold;">User Management</h1>
    </div>
</div>

{% block users-main %}
{% endblock %}


{% endblock %}

user_management/templates/login.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Gibush</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">

                    <div class="card-body p-0">
                        {% include "include/messages.html" %}
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <img class="col-lg-6" src="{% static 'icons/K9-icon.png' %}" alt="">
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Login</h1>
                                    </div>
                                    <form class="user" method="post">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <input type="text" class="form-control form-control-user" name="username"
                                                autofocus autocapitalize="none" autocomplete="username" maxlength="150"
                                                placeholder="Enter Username..." required value="guest_for_demo">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user"
                                                name="password" autocomplete="current-password" placeholder="Password"
                                                required value="Gg123456">
                                        </div>
                                        <input class="btn btn-primary btn-user btn-block" type="submit" value="Login">
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>

user_management/templates/users_menu.html
{% extends "home_users.html" %}
{% block users-main%}
{% load static %}
<div class="container-fluid">

    <div class="d-sm-flex align-items-center justify-content-between mb-4"><a
            href="{% url 'user_management:add-user-users' %}" class="d-inline-block btn btn-lg btn-primary shadow-sm"><svg
                xmlns="{% static 'icons/plus-lg.svg'%}" width="16" height="16" fill="currentColor" class="bi bi-plus-lg"
                viewBox="0 0 16 16">
                <path fill-rule="evenodd"
                    d="M8 2a.5.5 0 0 1 .5.5v5h5a.5.5 0 0 1 0 1h-5v5a.5.5 0 0 1-1 0v-5h-5a.5.5 0 0 1 0-1h5v-5A.5.5 0 0 1 8 2Z" />
            </svg> Add User</a></div>

    <!-- Content Row -->
    <div class="row">

        <!-- Earnins (Monthly) Card -->
        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text font-weight-bold text-success text-uppercase mb-1">
                                Users</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{users.all.count}}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Pending Requests Card -->
        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-danger shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text font-weight-bold text-danger text-uppercase mb-1">
                                Inactive Users</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{users.inactive.count}}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-user fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- DataTales -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h5 class="m-0 font-weight-bold text-primary">Users List</h5>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead class="text-gray-800">
                        <tr>
                            <th>Username</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Permissions</th>
                            <th>Is active</th>
                            <th>Is staff</th>
                            <th>Is superuser</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tfoot class="text-gray-800">
                        <tr>
                            <th>Username</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Permissions</th>
                            <th>Is active</th>
                            <th>Is staff</th>
                            <th>Is superuser</th>
                            <th></th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for user in users.all %}
                        <tr>
                            <th>{{ user.username }}</th>
                            <td>{{ user.first_name }}</td>
                            <td>{{ user.last_name }}</td>
                            <td>
                                {% with groups=user.groups.all %}

                                {% if groups %}
                                {% for group in groups %}
                                <span>{{group.name}}</span>
                                {% if forloop.last is False%}
                                <span>,</span>
                                {% endif %}

                                {% endfor %}
                                {% else %}
                                <span></span>

                                {% endif %}
                                {% endwith %}
                            </td>

                            {% if user.is_active %}
                            <td>
                                <img src="{% static 'icons/V-lg.svg' %}" alt="">
                            </td>
                            {% else %}
                            <td></td>
                            {% endif %}

                            {% if user.is_staff %}
                            <td>
                                <img src="{% static 'icons/V-lg.svg' %}" alt="">
                            </td>
                            {% else %}
                            <td></td>
                            {% endif %}

                            {% if user.is_superuser %}
                            <td>
                                <img src="{% static 'icons/V-lg.svg' %}" alt="">
                            </td>
                            {% else %}
                            <td></td>
                            {% endif %}

                            <td><a href="{% url 'user_management:edit-user-users' user.id %}"><button type="button"
                                        class="btn btn-outline-info"><svg xmlns="{% static 'icons/edit.svg' %}"
                                            width="16" height="16" fill="currentColor" class="bi bi-pencil-square"
                                            viewBox="0 0 16 16">
                                            <path
                                                d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z">
                                            </path>
                                            <path fill-rule="evenodd"
                                                d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z">
                                            </path>
                                        </svg></button></a></td>
                        </tr>
                        {% endfor%}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}