baror/urls.py
from django.urls import path
from . import views

app_name = 'barors'
urlpatterns = [
    path('', views.list_of_barors, name='all-barors'),
    path('addround/', views.add_baror, name='add-baror'),
    path('<pk>/editround/', views.edit_baror, name='edit-baror'),
    path('addsoldier/', views.add_soldier_to_round, name='add-soldier-to-round'),
    path('<pk>/barorReady/', views.baror_is_ready, name='baror-is-ready'),
    path('<pk>/manageround/', views.start_baror_page, name='start-baror'),
    path('<pk>/manageround/soldierendthebaror/', views.manage_running_round, name='manage-soldier-in-round'),
]

clinic/urls.py
from django.urls import path
from . import views

app_name = 'clinic'
urlpatterns = [
    path('', views.menu, name='menu-clinic'),
    path('search/', views.search, name='search-clinic'),
    path('<pk>/updatesoldier', views.update_soldier, name='update-soldier-clinic'), 
]

commander/urls.py
from django.urls import path
from . import views

app_name = 'commander'
urlpatterns = [
    path('', views.menu, name='menu-commander'),
    path('AcceptanceCriteria/', views.acceptance_criteria, name='acceptance-criteria-commander')
]

gibush/urls.py
from django.contrib import admin
from django.urls import path, include
from user_management import views
from django.conf.urls.static import static
from . import settings




urlpatterns = [
    path('admin/', admin.site.urls),
    # Home page
    path('', views.edit_home_path, name='edit-home-page'),
    path('home/', views.home_page, name='home-page'),
    # Apps
    path('soldiers/', include('soldiers.urls')),
    path('barors/', include('baror.urls')),
    path('shalishut/', include('shalishut.urls')),
    path('clinic/', include('clinic.urls')),
    path('commander/', include('commander.urls')),
    path('users/', include('user_management.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shalishut/urls.py
from django.urls import path
from . import views

app_name = 'shalishut'
urlpatterns = [
    path('', views.menu, name='menu-shalishut'),
    path('addsoldier/', views.add_soldier, name='add-soldier-shalishut'),
    path('<pk>/updatesoldier', views.update_soldier, name='update-soldier-shalishut'),
    path('<pk>/updatesoldier-ADMIN', views.update_soldier_admin, name='update-soldier-shalishut-admin'),
    path('search/', views.search, name='search-shalishut'),
]

user_management/urls.py
from django.urls import path
from . import views

app_name = 'user_management'
urlpatterns = [
    # Users
    path('', views.menu, name='menu-users'),
    path('adduser/', views.add_user, name='add-user-users'),
    path('edituser/<pk>', views.edit_user, name='edit-user-users'),
    path('search/', views.search, name='search-users'),
    path('login/', views.login_page, name='login-page'),
    path('logout/', views.logout_page, name='logout-page'),
    
    
]

templates/include/footer.html
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Amit Hauzer &copy; Gibush Management 2023 | Version: V3.0</span>
        </div>
    </div>
</footer>

templates/include/messages.html
{% if messages %}
{% load static %}
{% for message in messages %}
{% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
<div class="alert alert-primary">
  <img class="bi flex-shrink-0 me-2" src="{% static 'icons/messages_icons/info.svg' %}" alt="">{{ message }}
</div>
{% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
<div class="alert alert-success">
  <img class="bi flex-shrink-0 me-2" src="{% static 'icons/messages_icons/success.svg' %}" alt="">{{ message }}
</div>
{% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
<div class="alert alert-warning ">
  <img class="bi flex-shrink-0 me-2" src="{% static 'icons/messages_icons/error.svg' %}" alt="">{{ message }}
</div>
{% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
<div class="alert alert-danger">
  <img class="bi flex-shrink-0 me-2" src="{% static 'icons/messages_icons/error.svg' %}" alt="">{{ message }}
</div>
{% endif %}
{% endfor %}
{% endif %}

templates/include/side_bar.html
{% load static %}
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'home-page'%}">
    <div class="sidebar-brand-text mx-3">
      <img src="{% static 'icons/K9 icon without background_216x100.png'%}" width="150" alt="" />
    </div>
  </a>
  <!-- Divider -->
  <hr style="background-color: white;" class="sidebar-divider my-0">

  <li class="nav-item">
    <a class="nav-link" href="{% url 'home-page'%}">
      <span>Home</span>
    </a>
  </li>

  <!-- Divider -->
  <hr style="background-color: white;" class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading" style="font-size: 14px;">
    Departments
  </div>

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link" href="{% url 'shalishut:menu-shalishut' %}">
      <span>Shalishut</span>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'clinic:menu-clinic' %}">
      <span>Clinic</span>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'barors:all-barors' %}">
      <span>Barors</span>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'commander:menu-commander' %}">
      <span>Commander</span>
    </a>
  </li>

  <!-- Divider -->
  <hr style="background-color: white;" class="sidebar-divider my-0">

  <li class="nav-item">
    <a class="nav-link" href="{% url 'user_management:menu-users' %}">
      <span>User Management</span>
    </a>
  </li>


  <!-- Divider -->
  <hr style="background-color: white;" class="sidebar-divider">

  <!-- Sidebar Toggler (Sidebar) -->
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>

</ul>

templates/include/top_bar.html
{% load static%}
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

  <!-- Sidebar Toggle (Topbar) -->
  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
  </button>

  <!-- Topbar Search -->
  {% if search_url %}
  <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search"
    action="{% url search_url %}">
    <div class="input-group">
      <input type="search" class="form-control bg-light border-0 small" name="search" placeholder="Search..."
        aria-label="search" aria-describedby="basic-addon2">
      <div class="input-group-append">
        <button class="btn btn-primary" type="submit">
          <i class="fas fa-search fa-sm"></i>
        </button>
      </div>
    </div>
  </form>
  {% endif %}

  <!-- Topbar Navbar -->
  <ul class="navbar-nav ml-auto">

    <div class="topbar-divider d-none d-sm-block"></div>

    <!-- Nav Item - User Information -->
    {% if user.is_authenticated %}
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
        aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-user fa-fw mr-2 text-gray-700"></i>
        <span class="mr-2 d-none d-lg-inline text-gray-700">{{ user.username }}</span>
      </a>

      <!-- Dropdown - User Information -->
      <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
          <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
          Logout
        </a>
      </div>
    </li>

    {% else %}
    <div class="d-sm-flex align-items-center mb-1">
      <a href="{% url 'user_management:login-page' %}"><button
          class="d-sm-inline-block btn btn-primary shadow-sm">Login</button></a>
    </div>
    {% endif %}

  </ul>

</nav>