baror/urls.py
from django.urls import path
from . import views

app_name = 'barors'
urlpatterns = [
    path('', views.list_of_barors, name='all-barors'),
    path('addround/', views.add_baror, name='add-baror'),
    path('<pk>/editround/', views.edit_baror, name='edit-baror'),
    path('addsoldier/', views.add_soldier_to_round, name='add-soldier-to-round'),
    path('<pk>/barorReady/', views.baror_is_ready, name='baror-is-ready'),
    path('<pk>/manageround/', views.start_baror_page, name='start-baror'),
    path('<pk>/manageround/soldierendthebaror/', views.manage_running_round, name='manage-soldier-in-round'),
]

gibush/urls.py
from django.contrib import admin
from django.urls import path, include
from user_management import views
from django.conf.urls.static import static
from . import settings




urlpatterns = [
    path('admin/', admin.site.urls),
    # Home page
    path('', views.edit_home_path, name='edit-home-page'),
    path('home/', views.home_page, name='home-page'),
    # Apps
    path('soldiers/', include('soldiers.urls')),
    path('barors/', include('baror.urls')),
    path('shalishut/', include('shalishut.urls')),
    path('clinic/', include('clinic.urls')),
    path('commander/', include('commander.urls')),
    path('users/', include('user_management.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shalishut/urls.py
from django.urls import path
from . import views

app_name = 'shalishut'
urlpatterns = [
    path('', views.menu, name='menu-shalishut'),
    path('addsoldier/', views.add_soldier, name='add-soldier-shalishut'),
    path('<pk>/updatesoldier', views.update_soldier, name='update-soldier-shalishut'),
    path('<pk>/updatesoldier-ADMIN', views.update_soldier_admin, name='update-soldier-shalishut-admin'),
    path('search/', views.search, name='search-shalishut'),
]

shalishut/models.py
from django.db import models
from soldiers.models import Soldier


# Create your models here.
class Shalishut(models.Model):
    class ShalishutStatus(models.TextChoices):
        OPEN = 'Open', 'Open'
        DONE = 'Done', 'Done'
    class Profiletype(models.IntegerChoices):
        NINETY_SEVEN = 97, '97'
        EIGHTY_TWO = 82, '82'
        SEVENTY_TWO = 72, '72'
        
    soldier = models.OneToOneField(Soldier, max_length=50, on_delete=models.CASCADE)
    identity_num = models.CharField(max_length=9, null=True)
    firstname = models.CharField(max_length=20, null=True)
    lastname = models.CharField(max_length=20, null=True)
    city = models.CharField(max_length=50, null=True)
    profile = models.IntegerField(choices=Profiletype.choices, null=True)
    # kaba =
    # image = 
    shalishut_status = models.CharField(max_length=50, default=ShalishutStatus.OPEN, choices=ShalishutStatus.choices, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)



    def update_soldier_status(self):
        self.soldier.soldier_status = self.soldier.SoldierStatus.WAITING_FOR_CLINIC
        self.soldier.save()
        print(f'soldier status updated to: {self.soldier.soldier_status}.')



    def __str__(self) -> str:
        return f' IDF: {self.soldier.idf_num}, Name: {self.firstname} {self.lastname}, ID: {self.identity_num}, Soldier Status: {self.soldier.soldier_status}, City: {self.city}'

shalishut/views.py
from django.shortcuts import render, redirect
from soldiers.models import Soldier
from shalishut.models import Shalishut
from django.contrib import messages
from django.db.models import Q
from soldiers.utils import tasks_by_percent
from user_management.decorators import allowed_users, login_required


# @login_required
def menu(request):
    soldiers_before = Soldier.objects.filter(
        soldier_status=Soldier.SoldierStatus.WAITING_FOR_SHALISHUT)
    soldiers_after = Soldier.objects.exclude(
        soldier_status=Soldier.SoldierStatus.WAITING_FOR_SHALISHUT)
    percent = tasks_by_percent(after=soldiers_after, before=soldiers_before)
    return render(request, 'shalishut_menu.html', {'soldiers': {'before': soldiers_before, 'after': soldiers_after}, 'search_url': 'shalishut:search-shalishut', 'percent': percent})


@allowed_users(allowed_roles=['Shalishut'])
def add_soldier(request):
    if request.method == 'POST':
        idf_num = request.POST.get('idf_num')
        already_exist = Soldier.objects.filter(idf_num=idf_num)
        if already_exist:
            messages.error(request, 'Gibush number already exist.')
        else:
            try:
                soldier = Soldier(idf_num=idf_num)
                soldier.save()
                shalishut = Shalishut(soldier=soldier, profile=0)
                shalishut.save()
                messages.success(request, f'Soldier added successfully')
                return redirect('shalishut:menu-shalishut')
            except Exception as ex:
                messages.error(request, f'ERROR! {str(ex)}')
    return render(request, 'add_soldier.html')


@allowed_users(allowed_roles=['Shalishut'])
def update_soldier(request, pk):
    shalishut = Shalishut.objects.get(soldier=pk)
    # soldier = Soldier.objects.get(id=pk)
    if request.method == 'POST':
        shalishut.identity_num = request.POST.get('identity_num')
        shalishut.firstname = request.POST.get('first_name')
        shalishut.lastname = request.POST.get('last_name')
        shalishut.city = request.POST.get('city')
        shalishut.profile = request.POST.get('profile')
        try:
            shalishut.shalishut_status = Shalishut.ShalishutStatus.DONE
            shalishut.save()
            # update soldier status
            shalishut.update_soldier_status()
            messages.success(request, f'Soldier updated successfully')
            return redirect('shalishut:menu-shalishut')
        except Exception as ex:
            messages.error(request, f'ERROR! {str(ex)}')
    return render(request, 'update_shalishut_soldier.html', {'profiles': Shalishut.Profiletype, 'shalishut': shalishut})


@allowed_users(allowed_roles=['ShalishutAdmin'])
def update_soldier_admin(request, pk):
    shalishut = Shalishut.objects.get(soldier=pk)
    if request.method == 'POST':
        shalishut.identity_num = request.POST.get('identity_num')
        shalishut.firstname = request.POST.get('first_name')
        shalishut.lastname = request.POST.get('last_name')
        shalishut.city = request.POST.get('city')
        shalishut.profile = request.POST.get('profile')
        try:
            shalishut.shalishut_status = Shalishut.ShalishutStatus.DONE
            shalishut.save()
            messages.success(request, f'Soldier updated successfully')
            return redirect('shalishut:menu-shalishut')
        except Exception as ex:
            messages.error(request, f'ERROR! {str(ex)}')
    return render(request, 'update_shalishut_soldier_admin.html', {'profiles': Shalishut.Profiletype, 'shalishut': shalishut})


# @login_required
def search(request):
    search_req = request.GET.get('search')
    soldiers = Soldier.objects.filter(
        Q(shalishut__firstname__istartswith=search_req) |
        Q(shalishut__lastname__istartswith=search_req) |
        Q(idf_num__icontains=search_req) |
        Q(shalishut__identity_num__istartswith=search_req))
    soldiers_before = soldiers.filter(
        soldier_status=Soldier.SoldierStatus.WAITING_FOR_SHALISHUT)
    soldiers_after = soldiers.exclude(
        soldier_status=Soldier.SoldierStatus.WAITING_FOR_SHALISHUT)
    return render(request, 'shalishut_menu.html', {'soldiers': {'before': soldiers_before, 'after': soldiers_after}, 'search_url': 'shalishut:search-shalishut'})

shalishut/templates/add_soldier.html
{% extends "home_shalishut.html" %}
{% block shalishut-main %}
<div class="container-fluid">

    <div style="margin: auto;" class="col-lg-6">
        <!-- Collapsable Card Example -->
        <div class="card shadow mb-4">
            <!-- Card Header - Accordion -->
            <div class="d-block card-header py-3">
                <h3 class="m-0 font-weight-bold text-primary">Add Soldier</h3>
            </div>

            <!-- Card Content - Collapse -->
            <div class="collapse show" id="collapseCardExample">
                <div class="continer">
                    <div class="card-body">
                        <div class="form-group">
                            <div>Please, enter the soldier <strong>gibush</strong> number.</div><br>
                            <form class="form-control-lg" action="{% url 'shalishut:add-soldier-shalishut' %}" method="post">
                                {% csrf_token %}
                                <label for="idf_num">Idf Number: </label>
                                <input type="number" id="idf_num" min="1" max="500" name="idf_num" required><br><br>
                                <input class="btn btn-success float-end" type="submit" value="Add">
                            </form>
                            <a href="{% url 'shalishut:menu-shalishut' %}"><button
                                    class="btn btn-outline-secondary float-start mb-4">Back</button></a>
                        </div>
                        <br>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock%}

shalishut/templates/home_shalishut.html
{% extends "base.html" %}
{% block main %}
<div class="container-fluid">

    <!-- Page Heading -->
    <div style="text-align:center;" class="mb-4">
        <h1 class="mb-0 text-gray-800" style="font-weight: bold;">Shalishut</h1>
    </div>
</div>

{% block shalishut-main %}
{% endblock %}


{% endblock %}

shalishut/templates/shalishut_menu.html
{% extends "home_shalishut.html" %}
{% block shalishut-main %}
{% load static %}
<div class="container-fluid">

    <div class="d-sm-flex align-items-center justify-content-between mb-4"><a
            href="{% url 'shalishut:add-soldier-shalishut' %}" class="d-inline-block btn btn-lg btn-primary shadow-sm"><svg
                xmlns="{% static 'icons/plus-lg.svg'%}" width="16" height="16" fill="currentColor" class="bi bi-plus-lg"
                viewBox="0 0 16 16">
                <path fill-rule="evenodd"
                    d="M8 2a.5.5 0 0 1 .5.5v5h5a.5.5 0 0 1 0 1h-5v5a.5.5 0 0 1-1 0v-5h-5a.5.5 0 0 1 0-1h5v-5A.5.5 0 0 1 8 2Z" />
            </svg> Add Soldier</a></div>

    <!-- Content Row -->
    <div class="row">

        <!-- Pending Requests Card -->
        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text font-weight-bold text-warning text-uppercase mb-1">
                                Waiting List</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{soldiers.before.count}}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-user fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Earnins (Monthly) Card -->
        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text font-weight-bold text-success text-uppercase mb-1">
                                After Shalishut</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{soldiers.after.count}}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text font-weight-bold text-info text-uppercase mb-1">Tasks
                            </div>
                            <div class="row no-gutters align-items-center">
                                <div class="col-auto">
                                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{ percent }}%</div>
                                </div>
                                <div class="col">
                                    <div class="progress progress-sm mr-2">
                                        <div class="progress-bar bg-info" role="progressbar"
                                            style="width: {{ percent }}%" aria-valuenow="{{ percent }}"
                                            aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-list fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- DataTales -->
    {% if soldiers.before.count > 0 %}
    <div class="card border-left-warning shadow mb-4">
        <div class="card-header py-3">
            <h5 class="m-0 font-weight-bold text-primary">Waiting List</h5>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead class="text-gray-800">
                        <tr>
                            <th>IDF Number</th>
                            <th>Soldier Status</th>
                            <th> </th>
                        </tr>
                    </thead>
                    <tfoot class="text-gray-800">
                        <tr>
                            <th>IDF Number</th>
                            <th>Soldier Status</th>
                            <th> </th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for soldier in soldiers.before %}
                        <tr>
                            <th>{{ soldier.idf_num }}</th>
                            <td>{{ soldier.soldier_status }}</td>
                            <td><a href="{% url 'shalishut:update-soldier-shalishut' soldier.id %}"> <button
                                        type="button" class="btn btn-outline-info"><svg
                                            xmlns="{% static 'icons/edit.svg' %}" width="16" height="16"
                                            fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                            <path
                                                d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z">
                                            </path>
                                            <path fill-rule="evenodd"
                                                d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z">
                                            </path>
                                        </svg></button></a></td>
                        </tr>
                        {% endfor%}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {% endif %}
    <div class=" card shadow mb-4">
        <div class="card-header py-3">
            <h5 class="m-0 font-weight-bold text-primary">After Shalishut</h5>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead class="text-gray-800">
                        <tr>
                            <th>IDF Number</th>
                            <th>Name</th>
                            <th>Status</th>
                            <th>ID</th>
                            <th>City</th>
                            <th>Profile</th>
                            <th> </th>
                        </tr>
                    </thead>
                    <tfoot class="text-gray-800">
                        <tr>
                            <th>IDF Number</th>
                            <th>Name</th>
                            <th>Status</th>
                            <th>ID</th>
                            <th>City</th>
                            <th>Profile</th>
                            <th> </th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for soldier in soldiers.after %}
                        <tr>
                            <th>{{ soldier.idf_num }}</th>
                            <td>{{ soldier.shalishut.firstname }} {{ soldier.shalishut.lastname }}</td>
                            <td>{{ soldier.soldier_status }}</td>
                            <td>{{ soldier.shalishut.identity_num }}</td>
                            <td>{{ soldier.shalishut.city }}</td>
                            <td>{{ soldier.shalishut.profile }}</td>
                            <td><a href="{% url 'shalishut:update-soldier-shalishut-admin' soldier.id %}">
                                    <button type="button" class="btn btn-outline-info"><svg
                                            xmlns="{% static 'icons/edit.svg' %}" width="16" height="16"
                                            fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                            <path
                                                d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z">
                                            </path>
                                            <path fill-rule="evenodd"
                                                d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z">
                                            </path>
                                        </svg></button></a></td>
                        </tr>
                        {% endfor%}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>

{% endblock %}

shalishut/templates/update_shalishut_soldier.html
{% extends "home_shalishut.html" %}
{% block shalishut-main %}
<div class="container-fluid">

    <div style="margin: auto;" class="col-lg-6">
        <!-- Collapsable Card Example -->
        <div class="card shadow mb-4">
            <!-- Card Header - Accordion -->
            <div class="d-block card-header py-3">
                <h3 class="m-0 font-weight-bold text-primary">Update Soldier</h3>
            </div>

            <!-- Card Content - Collapse -->
            <div class="collapse show" id="collapseCardExample">
                <div class="continer">
                    <div class="card-body">
                        <div class="form-group">
                            <div>Complete the soldier's personal details.</div> <br>
                            <form class="form-control-lg" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <input type="hidden" id="soldier_pk" name="soldier_pk" value="{{soldier.id}}">
                                <label for="first_name">First name:</label><br>
                                <input type="text" id="first_name" name="first_name" required><br>
                                <label for="last_name">Last name:</label><br>
                                <input type="text" id="last_name" name="last_name" required><br>
                                <label for="identity_num">Identity num:</label><br>
                                <input type="text" id="identity_num" name="identity_num" minlength="9" maxlength="9"
                                    required><br>
                                <label for="city">City:</label><br>
                                <input type="text" id="city" name="city" required><br>
                                <label for="profile">Profile:</label>
                                <select id="profile" name="profile" required>
                                    <option value="">----</option>
                                    {% for p in profiles %}
                                    <option value="{{p}}">{{p}}</option>
                                    {% endfor %}s
                                </select><br><br>
                                <input class="btn btn-success float-end" type="submit" value="Update">

                            </form>
                        </div>
                        <br>
                            <a href="{% url 'shalishut:menu-shalishut' %}"><button
                                    class="btn btn-outline-secondary float-start mb-4">Back</button></a>
                        
                    </div>
                    <br>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

shalishut/templates/update_shalishut_soldier_admin.html
{% extends "home_shalishut.html" %}
{% block shalishut-main %}
<div class="container-fluid">

    <div style="margin: auto;" class="col-lg-6">
        <!-- Collapsable Card Example -->
        <div class="card shadow mb-4">
            <!-- Card Header - Accordion -->
            <div class="d-block card-header py-3">
                <h3 class="m-0 font-weight-bold text-primary">Update Soldier</h3>
            </div>

            <!-- Card Content - Collapse -->
            <div class="collapse show" id="collapseCardExample">
                <div class="continer">
                    <div class="card-body">
                        <div class="form-group">
                            <div>Edit the soldier's personal details. (only ShalishutAdmin)</div> <br>
                            <form class="form-control-lg" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <input type="hidden" id="soldier_pk" name="soldier_pk" value="{{soldier.id}}">
                                <label for="first_name">First name:</label><br>
                                <input type="text" id="first_name" name="first_name" value="{{shalishut.firstname}}"
                                    required><br>
                                <label for="last_name">Last name:</label><br>
                                <input type="text" id="last_name" name="last_name" value="{{shalishut.lastname}}"
                                    required><br>
                                <label for="identity_num">Identity num:</label><br>
                                <input type="text" id="identity_num" name="identity_num" minlength="9" maxlength="9"
                                    value="{{shalishut.identity_num}}" required><br>
                                <label for="city">City:</label><br>
                                <input type="text" id="city" name="city" value="{{shalishut.city}}" required><br>
                                <label for="profile">Profile:</label>
                                <select id="profile" name="profile" required>
                                    <option value="{{shalishut.profile}}">{{shalishut.profile}}</option>
                                    <option value="">----</option>
                                    {% for p in profiles %}
                                    <option value="{{p}}">{{p}}</option>
                                    {% endfor %}s
                                </select><br><br>
                                <input class="btn btn-success float-end" type="submit" value="Update">
                            </form>
                            <a href="{% url 'shalishut:menu-shalishut' %}"><button
                                    class="btn btn-outline-secondary float-start mb-4">Back</button></a>
                        </div>
                        <br>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

shalishut/templates/update_soldier.html
{% extends "base.html" %}
{% block content %}
<div class="container">

    <div class="row row-cols-1 row-cols-sm-1 row-cols-md-3 g-3">
        <div style="margin: auto;" class="col">
            <div class="card shadow-sm">

                <h1 style="text-align:center;">Update Soldier</h1>
                <form class="form-control form-control-lg" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="hidden" id="soldier_pk" name="soldier_pk" value="{{soldier.id}}">
                    <label for="first_name">First name:</label><br>
                    <input type="text" id="first_name" name="first_name" required><br>
                    <label for="last_name">Last name:</label><br>
                    <input type="text" id="last_name" name="last_name" required><br>
                    <label for="identity_num">Identity num:</label><br>
                    <input type="text" id="identity_num" name="identity_num" maxlength="9" required><br>
                    <label for="city">City:</label><br>
                    <input type="text" id="city" name="city" required><br>
                    <label for="cars">Profile:</label>
                    <select id="profile" name="profile" required>
                        {% for p in profiles %}
                        <option value="{{p}}">{{p}}</option>
                        {% endfor %}s
                    </select><br>
                    <!-- <label for="Picture">Picture:</label><br>
                    <input type=file name="picture"><br><br> -->


                    <input class="btn btn-success float-end" type="submit" value="Update">

                </form>
                <div class="card-body">

                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'shalishut:menu-shalishut' %}"><button type="button"
                                    class="btn btn-sm btn-outline-secondary">Back</button></a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}