baror/urls.py
from django.urls import path
from . import views

app_name = 'barors'
urlpatterns = [
    path('', views.list_of_barors, name='all-barors'),
    path('addround/', views.add_baror, name='add-baror'),
    path('<pk>/editround/', views.edit_baror, name='edit-baror'),
    path('addsoldier/', views.add_soldier_to_round, name='add-soldier-to-round'),
    path('<pk>/barorReady/', views.baror_is_ready, name='baror-is-ready'),
    path('<pk>/manageround/', views.start_baror_page, name='start-baror'),
    path('<pk>/manageround/soldierendthebaror/', views.manage_running_round, name='manage-soldier-in-round'),
]

gibush/urls.py
from django.contrib import admin
from django.urls import path, include
from user_management import views
from django.conf.urls.static import static
from . import settings




urlpatterns = [
    path('admin/', admin.site.urls),
    # Home page
    path('', views.edit_home_path, name='edit-home-page'),
    path('home/', views.home_page, name='home-page'),
    # Apps
    path('soldiers/', include('soldiers.urls')),
    path('barors/', include('baror.urls')),
    path('shalishut/', include('shalishut.urls')),
    path('clinic/', include('clinic.urls')),
    path('commander/', include('commander.urls')),
    path('users/', include('user_management.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

baror/models.py
from django.db import models
from datetime import datetime, timezone
from soldiers.models import Soldier

# Create your models here.
class BarOr(models.Model):
    class BarorStatus(models.TextChoices):
        WAITING_FOR_ALLOCATE = 'Waiting for allocate','Waiting for allocate'
        READY = 'Ready','Ready'
        RUNNING = 'Running','Running'
        DONE = 'Done','Done'

    baror_round = models.CharField(max_length=50 , unique=True)
    start_round_date = models.DateTimeField(null=True, blank=True)
    stop_round_date = models.DateTimeField(null=True, blank=True)
    baror_status = models.CharField(max_length=20 , default=BarorStatus.WAITING_FOR_ALLOCATE, choices=BarorStatus.choices)
    
    def set_start_time(self):
        # Adding start time and changing the status
        self.start_round_date = datetime.now(tz=timezone.utc)
        self.baror_status = self.BarorStatus.RUNNING
        self.save()
        print(self)

    def set_stop_time(self):
        # Adding stop time and changing the status
        self.stop_round_date = datetime.now(tz=timezone.utc)
        self.baror_status = self.BarorStatus.DONE
        self.save()
        print(self)
        print(f'{self.baror_round} has been finished')

    
    def __str__(self) -> str:
        return f"ROUND: {self.baror_round} - STATUS: {self.baror_status} - START TIME: {self.start_round_date} - STOP TIME:{self.stop_round_date}"


##################################################################################

class BarorScore(models.Model):
    baror_round = models.ForeignKey(BarOr, on_delete=models.CASCADE)
    soldier = models.ForeignKey(Soldier, on_delete=models.CASCADE)
    float_score = models.FloatField(max_length=200, null=True, blank=True)
    str_score = models.CharField(max_length=10, null=True, blank=True)

    def update_soldier_status_to_readey_to_running(self):
        self.soldier.soldier_status = self.soldier.SoldierStatus.READY_TO_RUN
        self.soldier.save()
        print(f'IDF number:{self.soldier.idf_num} - Status: {self.soldier.soldier_status} ')

    def update_soldier_status_to_running(self):
        self.soldier.soldier_status = self.soldier.SoldierStatus.RUNNING
        self.soldier.save()
        print(f'IDF number:{self.soldier.idf_num} - Status: {self.soldier.soldier_status} ')

    def update_score(self):
        # calculate time
        end_time = datetime.now(tz=timezone.utc)
        start_time = self.baror_round.start_round_date
        result = end_time.timestamp() - start_time.timestamp()
        # save in db
        self.float_score = result
        self.str_score = datetime.fromtimestamp(result, tz=timezone.utc).strftime("%H:%M:%S:%f")[:-4]
        self.save()
        self.soldier.soldier_status = self.soldier.SoldierStatus.AFTER_BAROR
        self.soldier.save()
        print(self)




    def __str__(self) -> str:
        return f'{self.baror_round} - {self.soldier} - {self.float_score} - {self.str_score}'

baror/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.db.models import Q
from soldiers.utils import tasks_by_percent
from .models import BarOr, BarorScore
from soldiers.models import Soldier
from user_management.decorators import allowed_users, login_required


# @login_required
def list_of_barors(request):
    barors = BarOr.objects.all()

    # for details
    soldiers_before = Soldier.objects.filter(
        Q(soldier_status=Soldier.SoldierStatus.WAITING_FOR_BAROR) |
        Q(soldier_status=Soldier.SoldierStatus.READY_TO_RUN)
        )
    soldiers_after = Soldier.objects.exclude(
        Q(soldier_status=Soldier.SoldierStatus.WAITING_FOR_CLINIC) |
        Q(soldier_status=Soldier.SoldierStatus.WAITING_FOR_SHALISHUT) |
        Q(soldier_status=Soldier.SoldierStatus.WAITING_FOR_BAROR) |
        Q(soldier_status=Soldier.SoldierStatus.MEDICALLY_DISQUALIFIED) |
        Q(soldier_status=Soldier.SoldierStatus.READY_TO_RUN)
        )
    percent = tasks_by_percent(after=soldiers_after, before=soldiers_before)

    return render(request, 'list_of_barors.html', {'soldiers': {'before': soldiers_before, 'after': soldiers_after}, 'barors': barors, 'percent': percent})


@allowed_users(allowed_roles=['Baror'])
def add_baror(request):
    barors_counter = BarOr.objects.count()
    try:
        baror = BarOr(baror_round=f'BarOr {barors_counter+1}')
        baror.save()
        messages.success(request, "Round added successfully")
    except Exception as ex:
        messages.error(request, f'ERROR! {str(ex)}')
    finally:
        return redirect('barors:all-barors')


@allowed_users(allowed_roles=['Baror'])
def edit_baror(request, pk):
    print(pk)
    baror = BarOr.objects.get(id=pk)
    soldiers = Soldier.objects.filter(soldier_status='Waiting for Baror')
    return render(request, 'edit_baror.html', {'baror': baror, 'soldiers': soldiers})


@allowed_users(allowed_roles=['Baror'])
def baror_is_ready(request, pk):
    # Get baror
    baror = BarOr.objects.get(id=pk)
    # Change status
    baror.baror_status = baror.BarorStatus.READY
    baror.save()
    # save
    print(f'{baror.baror_round} is ready')
    return redirect('barors:all-barors')


@allowed_users(allowed_roles=['Baror'])
def add_soldier_to_round(request):
    # Get params (POST)
    baror_id = request.POST.get('pk')
    soldier_id = request.POST.get('soldier_id')
    # Get Objects
    soldier = Soldier.objects.get(id=soldier_id)
    baror = BarOr.objects.get(id=baror_id)
    # Add to BarorScore
    baror_score = BarorScore(baror_round=baror, soldier=soldier)
    baror_score.save()
    # Update soldier's status
    baror_score.update_soldier_status_to_readey_to_running()
    print(f'Baror Score: {baror_score}')
    return redirect('barors:edit-baror', pk=baror_id)


@allowed_users(allowed_roles=['Baror'])
def start_baror_page(request, pk):
    # Get baror
    baror = BarOr.objects.get(id=pk)
    barorscores = BarorScore.objects.all().filter(
        baror_round=pk).order_by('float_score')
    if request.method == 'POST':
        # add baror start date and update status
        baror.set_start_time()
        # update soldiers' status
        for score in barorscores:
            score.update_soldier_status_to_running()
    return render(request, 'baror_round.html', {'baror': baror, 'barorscores': barorscores})


@allowed_users(allowed_roles=['Baror'])
def manage_running_round(request, pk):
    # Get data
    if request.method == 'POST':
        soldier_id = request.POST.get('soldier_id')
        barorscore = BarorScore.objects.get(baror_round=pk, soldier=soldier_id)
        barorscore.update_score()

        # check if baror has been finished
        barorscores = BarorScore.objects.all().filter(baror_round=pk, float_score=None)
        if not barorscores:
            baror = BarOr.objects.get(id=pk)
            baror.set_stop_time()
            return redirect('barors:all-barors')
    return redirect('barors:start-baror', pk=pk)

baror/templates/baror_round.html
{% extends "home_baror.html" %}
{% block baror-main %}
<div class="container-fluid">

  <!-- DataTales -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h2 class="m-0 font-weight-bold text-primary">ROUND: {{ baror.baror_round }}</h2>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <h3 style="text-align: center" class="top">
            {% if baror.start_round_date is None %}
            <form action="{% url 'barors:start-baror' baror.id %}" method="post">
              {% csrf_token %}
              <button class="btn btn-lg btn-success">Start</button>
            </form>
            {% else %}
            <div>Start time: {{ baror.start_round_date }}</div>

            {% endif %}
          </h3>

          <thead class="text-gray-800">
            <tr>
              <th>IDF Number</th>
              <th>Baror Score</th>
              <th> </th>
            </tr>
          </thead>
          <tfoot class="text-gray-800">
            <tr>
              <th>IDF Number</th>
              <th>Baror Score</th>
              <th> </th>
            </tr>
          </tfoot>
          <tbody>
            {% for score in barorscores %}

            <tr>
              <th>{{ score.soldier.idf_num }}</th>
              <td>{{ score.str_score }}</td>

              <td>
                {% if baror.start_round_date is None %}

                {% elif score.str_score is None %}
                <form action="{% url 'barors:manage-soldier-in-round' baror.id %}" method="post">
                  {% csrf_token %}
                  <input type="hidden" id="pk" name="pk" value="{{baror.id}}">
                  <input type="hidden" id="soldier_id" name="soldier_id" value="{{score.soldier.id}}">
                  <button class="btn btn-secondary">Done</button>
                </form>
                {% else %}
                <button class="btn btn-outline-secondary" disabled>Done</button>
                {% endif %}
              </td>
              {% endfor%}
          </tbody>
        </table>
      </div>
      <div>
        {% if baror.start_round_date is None %}
        <a href="{% url 'barors:all-barors' %}"><button class="btn btn-outline-secondary">Back</button></a>
        {% elif baror.start_round_date != None and baror.stop_round_date != None %}
        <a href="{% url 'barors:all-barors' %}"><button class="btn btn-outline-secondary">Back</button></a>
        {% endif %}
      </div>
    </div>

  </div>

</div>
{% endblock%}

baror/templates/edit_baror.html
{% extends "home_baror.html" %}
{% block baror-main %}
<div class="container-fluid">


    <!-- DataTales -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h3 class="m-0 font-weight-bold text-primary">Edit - {{ baror.baror_round }}</h3>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead class="text-gray-800">
                        <tr>
                            <th>IDF Number</th>
                            <th>Soldier status</th>
                            <th> </th>
                        </tr>
                    </thead>
                    <tfoot class="text-gray-800">
                        <tr>
                            <th>IDF Number</th>
                            <th>Soldier status</th>
                            <th> </th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for soldier in soldiers%}

                        <tr>
                            <th>{{ soldier.idf_num }}</th>
                            <td>{{ soldier.soldier_status }}</td>

                            <td>
                                <form action="{% url 'barors:add-soldier-to-round' %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" id="pk" name="pk" value="{{baror.id}}">
                                    <input type="hidden" id="soldier_id" name="soldier_id" value="{{soldier.id}}">
                                    <button class="btn btn-info">Add</button>
                                </form>
                            </td>
                            {% endfor%}
                    </tbody>
                </table>
            </div>
            <div>
                <a href="{% url 'barors:all-barors' %}"><button class="btn btn-outline-secondary">Back</button></a>
                {% if baror.barorscore_set.all %}
                <a href="{% url 'barors:baror-is-ready' baror.id %}"><button class="btn btn-success">finish</button></a>
                {% endif%}
            </div>
        </div>

    </div>

</div>
{% endblock%}

baror/templates/home_baror.html
{% extends "base.html" %}
{% block main %}
<div class="container-fluid">

    <!-- Page Heading -->
    <div style="text-align:center;" class="mb-4">
        <h1 class="mb-0 text-gray-800" style="font-weight: bold;">Barors</h1>
    </div>
</div>

{% block baror-main %}
{% endblock %}


{% endblock %}

baror/templates/list_of_barors.html
{% extends "home_baror.html" %}
{% block baror-main %}
{% load static %}
<div class="container-fluid">

    <div class="d-sm-flex align-items-center justify-content-between mb-4"><a href="{% url 'barors:add-baror' %}"
            data-toggle="modal" data-target="#addBarorModal" class="d-inline-block btn btn-lg btn-primary shadow-sm"><svg
                xmlns="{% static 'icons/plus-lg.svg'%}" width="16" height="16" fill="currentColor" class="bi bi-plus-lg"
                viewBox="0 0 16 16">
                <path fill-rule="evenodd"
                    d="M8 2a.5.5 0 0 1 .5.5v5h5a.5.5 0 0 1 0 1h-5v5a.5.5 0 0 1-1 0v-5h-5a.5.5 0 0 1 0-1h5v-5A.5.5 0 0 1 8 2Z" />
            </svg> Add Round</a>
    </div>


    <div class="row">
        
        <!-- Pending Requests Card -->
        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text font-weight-bold text-warning text-uppercase mb-1">
                                Waiting List</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{soldiers.before.count}}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-user fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <!-- Earnins (Monthly) Card -->
        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text font-weight-bold text-success text-uppercase mb-1">
                                After Baror</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{soldiers.after.count}}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text font-weight-bold text-info text-uppercase mb-1">Tasks
                            </div>
                            <div class="row no-gutters align-items-center">
                                <div class="col-auto">
                                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{ percent }}%</div>
                                </div>
                                <div class="col">
                                    <div class="progress progress-sm mr-2">
                                        <div class="progress-bar bg-info" role="progressbar"
                                            style="width: {{ percent }}%" aria-valuenow="{{ percent }}"
                                            aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-list fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- DataTales -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h3 class="m-0 font-weight-bold text-primary">List of Barors</h3>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead class="text-gray-800">
                        <tr>
                            <th>Round</th>
                            <th>Baror Status</th>
                            <th>Soldiers In Round</th>
                            <th> </th>
                        </tr>
                    </thead>
                    <tfoot class="text-gray-800">
                        <tr>
                            <th>Round</th>
                            <th>Baror Status</th>
                            <th>Soldiers In Round</th>
                            <th> </th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for baror in barors %}
                        <tr>
                            <td>{{ baror.baror_round }}</td>
                            <td>{{ baror.baror_status }}</td>
                            <td>
                                {% with barorscoers=baror.barorscore_set.all %}

                                {% if barorscoers %}
                                {% for barorscore in barorscoers %}
                                <span>{{barorscore.soldier.idf_num}}</span>
                                {% if forloop.last is False%}
                                <span>,</span>
                                {% endif %}
                                {% endfor %}
                                {% else %}
                                <span>None</span>

                                {% endif %}
                                {% endwith %}
                            </td>
                            <td>
                                {% if baror.baror_status == "Waiting for allocate" %}
                                <a href="{% url 'barors:edit-baror' baror.id %}"><button
                                        class="btn btn-sm btn-light">Edit</button></a>
                                {% elif baror.baror_status == "Ready"%}
                                <a href="{% url 'barors:edit-baror' baror.id %}"><button
                                        class="btn btn-sm btn-light">Edit</button></a>
                                <a href="{% url 'barors:start-baror' baror.id %}"><button
                                        class="btn btn-sm btn-success">Let's
                                        go!</button></a>
                                {% elif baror.baror_status == "Running"%}
                                <button class="btn btn-sm btn-light" disabled>Edit</button>
                                <a href="{% url 'barors:start-baror' baror.id %}"><button
                                        class="btn btn-sm btn-success">open</button></a>
                                {% elif baror.baror_status == "Done"%}
                                <button class="btn btn-sm btn-light" disabled>Edit</button>
                                <a href="{% url 'barors:start-baror' baror.id %}"><button
                                        class="btn btn-sm btn-secondary">View</button></a>
                                {% endif %}
                            </td>

                        </tr>

                        {% endfor%}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>

<!-- Add Baror Modal-->
<div class="modal fade" id="addBarorModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Are you sure?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Please, check if there isn't a baror with status 'Waiting for allocate'.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="{% url 'barors:add-baror' %}">Add</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}